KNOWN_STORAGES = [
    "Velia",
    "Olvia",
    "Isla de Illya",
    "Heidel",
    "Glish",
    "Calpheon",
    "Keplan",
    "Puerto de Epheria",
    "Trent",
    "Altinova",
    "Tarif",
    "Valencia",
    "Shakatu",
    "Bazar Granos de Arena",
    "Puerto Interior de Ancado",
    "Arehaza",
    "Muiquun",
    "Grana",
    "Árbol de la Sabiduría",
    "Duvencrune",
    "Odraxia",
    "Ojo de Okilua",
    "Aldea de Eil",
    "Mudeul (Nampo)",
    "Dalbeol",
    "Byeot (Nopsae)",
    "Avenida Yukjo",
    "Godu",
    "Bukpo",
    "Muzgar",
    "Asparkan",
    "Belander",
    "Templo de Hakinza",
]